### ISSUE TITLE
Problems with gnome shell when maximized

### ISSUE THREAD

**Issue by hirseboy** [antonypro/QGoodWindow#49] opened 2024-01-07 21:14 UTC
I have graphic glitches with gnome-shell (ubuntu 22-04) whit the app in maximized mode. Do you also have this problem?

**Comment by antonypro** [comment] 2024-01-12 02:14
Hi, @hirseboy!

I couldn't reproduce the problem with version 2.4.3-beta1, because it doesn't compile on Linux due to a bug.

Please try beta2: https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.3-beta2

I didn't have seen any glitches.

However, if you see that the glitch persists, please give a screenshot!

Thanks!

**Comment by SkorokhodovVA** [comment] 2024-01-19 03:23
@antonypro 
https://youtu.be/UfFyYdML998

**Comment by hirseboy** [comment] 2024-01-26 08:30
yes, thats the same glitching happening at my gnome-shell.

**Comment by antonypro** [comment] 2024-01-26 09:03
@SkorokhodovVA: Hi! I'm posting the video here on GitHub for those who doesn't want to go to YouTube!


https://github.com/antonypro/QGoodWindow/assets/8022463/4f4d6438-102e-4d42-8062-18d7f2a9eb9b

**Comment by antonypro** [comment] 2024-01-26 09:14
Hi, @hirseboy!

I couldn't be able to reproduce the problem for some reason, however after see the @SkorokhodovVA video, i think the problem is that the mask responsible for drawing rounded corners on Linux is applied too early or too late sometimes.

An attempt to solve this problem was done on `QGoodWindow-2.4.3-beta3` : https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.3-beta3

If you could, please give a feedback if the problem was solved or not.

Thanks!

**Comment by hirseboy** [comment] 2024-01-26 09:22
https://github.com/antonypro/QGoodWindow/assets/58851829/6323f8e0-ab07-476f-a9a1-6c058c1ac487

Still the same for me unfortunately ...

**Comment by antonypro** [comment] 2024-01-26 14:29
@hirseboy: I've made changes to `QGoodWindow` that basically apply a mask to the window even when the window is maximized or full screen, but a rectangular mask with no rounded corners in such cases.

I'm also created a dedicated folder to this issue:
https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.3-issue49

If you could, please give a feedback if this solves the problem or not.

Thanks!

**Comment by hirseboy** [comment] 2024-01-26 14:35
Seems to be working fine so far! :+1:  
Did not see any glitches

**Comment by hirseboy** [comment] 2024-01-26 14:44
The only bug I found was the comboBox items width (Sorry the screenrecorder broke the ratio and produced glitches - no QGoodWindow bug)

https://github.com/antonypro/QGoodWindow/assets/58851829/228a5686-e012-48c6-b4d0-0f88da35bb2f

**Comment by antonypro** [comment] 2024-01-26 16:19
@hirseboy:

I'm glad to know that this bug appears to be solved!

What is going wrong, maybe, is the interpretation of what is a `null` mask in a specific environment.

Thanks for report the bug!

**Comment by antonypro** [comment] 2024-02-16 00:33
Hi, @hirseboy!

I'm going to close this issue because the solution is present in version 2.4.3.
If you believe that are problems remaining, please ask to reopen this issue or open a new issue.

Thanks!

**Closed as completed by antonypro** 2024-02-16 00:33 UTC
Labels: bug
