### ISSUE TITLE
Ubuntu 16.04 - X11 - Resize/Move impossible

### ISSUE THREAD

**Issue by BrnSlr** [antonypro/QGoodWindow#14] opened 2022-07-27 10:23 UTC
It's not possible to resize or move a window on Ubuntu 16.04 using X11

Is it expected ?

**Comment by antonypro** [comment] 2022-08-12 01:58
@BrnSlr: No. It should work! However I'm unable to reproduce the problem, in my attempts it works well.

Do you see this problem in another environment?

Please see: https://github.com/antonypro/QGoodWindow/issues/13#issuecomment-1212654623

Thanks.

**Comment by antonypro** [comment] 2022-12-29 23:57
Closing due to inability to reproduce the problem.

**Closed as completed by antonypro** 2022-12-29 23:57 UTC
