### ISSUE TITLE
Gtk calls errors on Ubuntu 16.04 - X11

### ISSUE THREAD

**Issue by BrnSlr** [antonypro/QGoodWindow#13] opened 2022-07-27 10:22 UTC
Out of the box on Ubuntu 16.04 (QT5.15.2), the example project crashes week using x11 following the gtk calls from 
`bool QGoodWindow::isSystemThemeDark()`

Outputs

```
(process:11737): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:11737): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(process:11737): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:11737): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Comment by antonypro** [comment] 2022-08-12 01:52
@BrnSlr: Hi! I've tried with no luck reproduce the problem described on Ubuntu 16.04 e Qt 5.15 (by the way a pain to get it working).

What i did was install the Qt 5.15, installed the packages mentioned on the README of this project, upgrade GCC\G++ to version 7.5.0 and installed an older version of Qt Creator. Everything worked.

What i suggest to you is consider an upgrade of OS or use an older version of Qt.

If you are using this system only as target, please consider using some deploy tool for this.

Do you see this problem in another environment?

Thanks.

**Comment by antonypro** [comment] 2022-12-29 23:56
Closing due to inability to reproduce the problem.

**Closed as completed by antonypro** 2022-12-29 23:56 UTC
