### ISSUE TITLE
Is there any plan to support Qt's scaling strategy?

### ISSUE THREAD

**Issue by jxiaow** [antonypro/QGoodWindow#25] opened 2023-02-01 08:48 UTC
Is there any plan to support Qt's scaling strategy?

`QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling); `
  `QGuiApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);`
  `QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);`

**Comment by kresimirko** [comment] 2023-02-01 08:52
I can't be the one to say anything, but the author did say this: https://github.com/antonypro/QGoodWindow/issues/19#issuecomment-1366054300

**Comment by jxiaow** [comment] 2023-02-01 09:06
Because most applications now need to adapt to 2k or 4k high-definition screens, but I read the author's reply and the zoom function of Qt is turned off by default

**Comment by jxiaow** [comment] 2023-02-01 09:08
I hope to support or provide some ideas, thanks @antonypro

**Comment by Renleilei1992** [comment] 2023-02-07 13:44
high dpi support is indeed necessary,  but it's a terrible work to adapt it.

**Comment by antonypro** [comment] 2023-02-07 17:21
@jxiaow, @kresimirko  and @Renleilei1992:

Due to demand I'm going to start attempts to support automatic scaling, it's really hard, but i will notice you when it goes to be implemented or if the idea is abandoned.

Thanks all!

**Comment by jxiaow** [comment] 2023-02-15 08:20
@antonypro thanks, i will look forward to your notification。

**Comment by antonypro** [comment] 2023-02-17 15:34
@jxiaow, @kresimirko and @Renleilei1992: This feature was added on version 2.3.

**Comment by antonypro** [comment] 2023-02-24 02:09
I believe the issue is resolved, so I am closing this issue.

**Closed as completed by antonypro** 2023-02-24 02:09 UTC
Labels: enhancement
